--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SOF3/libglocal
projects:
  LibglocalExample:
    path: LibglocalExample/
  libglocal:
    path: libglocal/
    model: virion
    type: library
...
